export const clubs = ["Astronomy", "Coding", "Debating", "Quizzinga", "Robotics", "Startups", "Fun Events", "Web3", "ASME"];

export const events = [
  {
    "id": "0",
    "name": "",
    "club": "",
    "participation": "",
    "imgName": "",
    "poster": "",
    "about": "",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 999,
    "contacts":
      [
        {
          "name": "",
          "number": "",
          "email": "",
        },
        {
          "name": "",
          "number": "",
          "email": "",
        },
        {
          "name": "",
          "number": "",
          "email": "",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "1",
    "name": "ASTROHUNT",
    "club": "Astronomy",
    "participation": "Team Participation",
    "imgName": "./images/events/astronomy/astrohunt/image.jpg",
    "poster": "/images/events/astronomy/astrohunt/poster.jpg",
    "about": "Astro-Hunt is an astronomy-themed treasure hunt where you will come across mind boggling riddles, and to get closer to the finishing line, you will have to be faster than your competitors both in solving the riddles and in terms of reaching the next location.",
    "structure": "An exciting hunt with a pinch of Astronomy!",
    "prizes": "Prize Pool of 20,000/-",
    "timeline": "09:00 AM to 13:00 PM on January 28th, 2023",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Shubhankar Bhatt",
          "number": "+91 9997078807",
          "email": "20UEC129@lnmiit.ac.in",
        },
        {
          "name": "Radhika Agarwal",
          "number": "+91 74518 47047",
          "email": "20UCC083@lnmiit.ac.in",
        },
        {
          "name": "Vaibhav Khamesra",
          "number": "+91 70236 59757",
          "email": "21UCS224@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17Rmi03aB5-fmxWbvhjAJapWq6K10gYme/view?usp=share_link",
    "link": "",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "2",
    "name": "ASTROMEMIA",
    "club": "Astronomy",
    "participation": "Solo Participation",
    "imgName": "./images/events/astronomy/astromemia/image.jpg",
    "poster": "/images/events/astronomy/astromemia/poster.jpg",
    "about": "An online meme-making contest where you can use your understanding of astronomy and humour to make a meme that gets everyone in the room smiling. And anyway, what could be better than laughing while also winning something?",
    "structure": "Online Meme-Making competition themed on Astronomy.",
    "prizes": "Prizes Worth 10K!",
    "timeline": "13 January 2023 - Contest Starts 20 January 2023 - Submissions Close",
    "payment": 0,
    "contacts":
      [
        {
          "name": "Aman Aggawral",
          "number": "+91 73001 76925",
          "email": "20UME006@lnmiit.ac.in",
        },
        {
          "name": "Rudransh Sharma",
          "number": "+91 95991 35384",
          "email": "20UME043@lnmiit.ac.in",
        },
        {
          "name": "Ashwin Singh",
          "number": "+91 84128 11538",
          "email": "21UCC128@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17PlRzH0VoFvmGduWgDuNh0u04yA9Lrjn/view?usp=share_link",
    "link": "https://unstop.com/creative-cultural-event/astromemia-lnm-institute-of-information-technology-lnmiit-jaipur-585840",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "3",
    "name": "BRAHMAAND",
    "club": "Astronomy",
    "participation": "Team Participation",
    "imgName": "./images/events/astronomy/brahmaand/image.jpg",
    "poster": "/images/events/astronomy/brahmaand/poster.jpg",
    "about": "Brahmaand is an event where you present your frame of reference towards the problem statement and come with effective ways or solutions with the help of proven resources.",
    "structure": "Presentation making competition conducted in two rounds. Shortlisted candidates from the online round will be asked to present in offline mode in LNMIIT.",
    "prizes": "Prizes Worth 15K!",
    "timeline": "17:00 PM, 13 January 2023 - Problem statement will be released 23:59 PM, 15 January 2023 - Submission Deadline, 16:00 PM, 27 January 2023 - Shortlisted teams will get a chance to present their case studies to judges in offline mode",
    "payment": 0,
    "contacts":
      [
        {
          "name": "Aryan Aditya",
          "number": "+91 95999 77381",
          "email": "20UCS031@lnmiit.ac.in",
        },
        {
          "name": "Ayush Kumar Dhoot",
          "number": "+91 83687 14482",
          "email": "20UCS045@lnmiit.ac.in",
        },
        {
          "name": "Sai Ruthvik",
          "number": "+91 86882 74747",
          "email": "21UCS174@lnnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1kQxHnhn--ySWVMdAhFd2owXbL2xlC1Dt/view",
    "link": "https://unstop.com/competition/brahmaand-lnm-institute-of-information-technology-lnmiit-jaipur-584783",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "4",
    "name": "DHOOMKETU",
    "club": "Astronomy",
    "participation": "Solo Participation",
    "imgName": "./images/events/astronomy/dhoomketu/image.jpg",
    "poster": "/images/events/astronomy/dhoomketu/poster.png",
    "about": "Want to relax a little bit and take a break from the everyday hustle? The Astronomy club brings for you the Sky gazing session with many short and exciting events such as telescope handling, jamming sessions, poetry sessions, discussions on mythology, astrophysics and a lot more.",
    "structure": "A relaxing and entertaining event having telescopic handling, jamming sessions, poetry sessions, etcetera.",
    "prizes": "",
    "timeline": "20:00 PM Onwards on 27th January 2023 and 28th January 2023",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Abhi Sanghi",
          "number": "+91 96106 32595",
          "email": "20DEC001@lnmiit.ac.in",
        },
        {
          "name": "Maanas Gupta",
          "number": "+91 73183 74333",
          "email": "21UCS120@lnmiit.ac.in",
        },
        {
          "name": "Ayush Bajaj",
          "number": "+91 76783 07965",
          "email": "21UCC129@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17WKj7_woMQJF4zot30EwvW3Qmw3zfPE4/view",
    "link": "",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "6",
    "name": "STARPIX",
    "club": "Astronomy",
    "participation": "Solo Participation",
    "imgName": "./images/events/astronomy/starpix/image.jpg",
    "poster": "/images/events/astronomy/starpix/poster.jpg",
    "about": "Astrophotography bridges the gap between art and science, highlighting the natural beauty of our Universe. The Astronomy club of LNMIIT brings you an online Astrophotography event for all the stargazers and astrophotographers! Get your gear all set to capture the colors within the night sky and submit them to us with a short description.",
    "structure": "Online Astrophotography Event.",
    "prizes": "Prizes Worth 15K!",
    "timeline": "13th January 2023 to 23rd January 2023",
    "payment": 0,
    "contacts":
      [
        {
          "name": "Shubhankar Bhatt",
          "number": "+91 99970 78807",
          "email": "20uec129@lnmiit.ac.in",
        },
        {
          "name": "Manan Mishra",
          "number": "+91 73405 31368",
          "email": "20ucc062@lnmiit.ac.in",
        },
        {
          "name": "Parth Somani",
          "number": "+91 87668 96322",
          "email": "21dcs007@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/17KJjELmwiHi-XS9HrSZ8SQvAc3Q6Qgin/view?usp=share_link",
    "link": "https://unstop.com/creative-cultural-event/starpix-lnm-institute-of-information-technology-lnmiit-jaipur-585843",
    "clubemail": "astronomyclub@lnmiit.ac.in",
  },
  {
    "id": "7",
    "name": "C-PEAK",
    "club": "Coding",
    "participation": "Solo Participation",
    "imgName": "./images/events/cybros/c-peak/image.jpg",
    "poster": "/images/events/cybros/c-peak/poster.jpg",
    "about": "C-PEAK is an elimination tournament. Each round will be a normal one-person competitive programming contest in which the bottom half of the standing will be eliminated and the top half will qualify for the next round.",
    "structure": "",
    "prizes": "Top rankers will get Exciting goodies",
    "timeline": "27-28 January 2023",
    "payment": 0,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "https://docs.google.com/forms/d/e/1FAIpQLScyBNYmg_JE_cXgOFUNWobtDqshR1wAlIXZuq73Uz2HUyi6jQ/viewform",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "8",
    "name": "CP DUELS",
    "club": "Coding",
    "participation": "Solo Participation",
    "imgName": "./images/events/cybros/cpduels/image.jpg",
    "poster": "/images/events/cybros/cpduels/poster.jpg",
    "about": "CP DUEL is an in-person 1v1 knockout tournament. As the meaning of “duel” suggests this will be a “coding combat” between 2 individuals i.e both the participants will be given the same problem and the first person to solve it wins.",
    "structure": "1V1 with fast thinking",
    "prizes": "Top rankers will get Exciting goodies",
    "timeline": "27-28 January 2023",
    "payment": 0,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "https://docs.google.com/forms/d/e/1FAIpQLSdLHc7PArUSnDiZbSU7RKa5PtuL376AZV2p3VYkcbWZQihaZQ/viewform",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "9",
    "name": "ENIGMA",
    "club": "Coding",
    "participation": "Solo Participation",
    "imgName": "./images/events/cybros/enigma/image.jpg",
    "poster": "/images/events/cybros/enigma/poster.jpg",
    "about": "This is Cybros’ flagship rated contest. It is a normal one-person competitive programming contest. This is an onsite round in addition to the official rated round in Codeforces.",
    "structure": "Onsite competitive programming contest",
    "prizes": "Prizes Worth 30K",
    "timeline": "19 December 2022 - Online round concluded 29 January 2023 - Onsite Round",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "https://docs.google.com/forms/d/e/1FAIpQLSeETAUcVCXd0iytIqI4xQkN-c3Rbkw0ayDXrTSYZed2YCVmkQ/viewform",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "10",
    "name": "IUPC",
    "club": "Coding",
    "participation": "Team Participation",
    "imgName": "./images/events/cybros/iupc/image.jpg",
    "poster": "/images/events/cybros/iupc/poster.jpg",
    "structure": "ICPC Structure with Team Size of Max 3 Members",
    "prizes": "Prizes Worth 50K",
    "timeline": "28th January 2023",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Astha Singh",
          "number": "+91 63765 79645",
          "email": "20ucs040@lnmiit.ac.in",
        },
        {
          "name": "Shivral Somani",
          "number": "+91 63768 22085",
          "email": "20ucs184@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://docs.google.com/document/d/1Z_0ZrqXATSKFc239i15f7O4zVW-Iy1uS/edit?usp=sharing&ouid=103682676179344015200&rtpof=true&sd=true",
    "link": "https://docs.google.com/forms/d/e/1FAIpQLSe4cE-hQrO0pQRaGb5LxHkLjm5_XXlInrN36BFmu1Bnd5Ggug/viewform",
    "clubemail": "cybrosclub@lnmiit.ac.in",
  },
  {
    "id": "12",
    "name": "Plinth's MUN'23",
    "club": "Debating",
    "participation": "Solo Participation",
    "imgName": "./images/events/debsoc/plinth_mun23/image.jpg",
    "poster": "/images/events/debsoc/plinth_mun23/poster.jpg",
    "about": "At a MUN conference, delegates(students) will each represent a nation/organization to solve world problems working with other delegates. The event will be 2 days long and will have UNGA, AIPPM and UNSC as the committees.",
    "structure": "Model United Nations Organisation Conference",
    "prizes": "PMUN'23 has got a massive prize pool of Rs. 92,000/-",
    "timeline": "Application deadline: 21st Jaunary 2023     Conference dates: 27th January 2023 and 28th January 2023",
    "payment": 1200,
    "contacts":
      [
        {
          "name": "Arjun Saxena",
          "number": "+91 95714 85158",
          "email": "20ucc021@lnmiit.ac.in",
        },
        {
          "name": "Divyanshi Gautam",
          "number": "+91 94624 21299",
          "email": "20ucs066@lnmiit.ac.in",
        },
        {
          "name": "Saumya Kalra",
          "number": "+91 6375 548121",
          "email": "20uec119@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1SbMYQCSguU2ROVODph3KJKTkyllw9lTm/view",
    "link": "https://docs.google.com/forms/d/e/1FAIpQLSdlckbELXlJ0XCuFyEiSSaXldr7VaDOqUfzTt7hSI4slc10AQ/viewform",
    "clubemail": "debsoc@lnmiit.ac.in",
  },
  {
    "id": "11",
    "name": "Change My Mind",
    "club": "Debating",
    "participation": "Solo/Team Participation",
    "imgName": "./images/events/debsoc/changemymind/image.jpg",
    "poster": "/images/events/debsoc/changemymind/poster.jpg",
    "about": "\"Change My Mind\" event is a public discussion forum where individuals will be presented with a random opinion to which you’ll have to convince the chair with argumentation to adhere to your own thoughts on the topic.",
    "structure": "On site passively-aggressive refutal",
    "prizes": "The winners will be awarded prizes, goodies and vouchers worth Rs. 6000/-.",
    "timeline": "27th, 28th and 29th January 2023",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Arjun Saxena",
          "number": "+91 95714 85158",
          "email": "20ucc021@lnmiit.ac.in",
        },
        {
          "name": "Divyanshi Gautam",
          "number": "+91 94624 21299",
          "email": "20ucs066@lnmiit.ac.in",
        },
        {
          "name": "Saumya Kalra",
          "number": "+91 6375 548121",
          "email": "20uec119@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1nZtXPLpR5vT78HMNWDVkrw1_HyV-N33E/view?usp=share_link",
    "link": "",
    "clubemail": "debsoc@lnmiit.ac.in",
  },
  {
    "id": "13",
    "name": "Graffiti Wall",
    "club": "Debating",
    "participation": "Solo Participation",
    "imgName": "./images/events/debsoc/graffitiwall/image.jpg",
    "poster": "/images/events/debsoc/graffitiwall/poster.jpg",
    "about": "Graffiti wall will give an opportunity to the viewers to actually put their thoughts via a sheet of paper or drawings on a blank canvas.",
    "structure": "On site idea centric graffiti",
    "prizes": "",
    "timeline": "27th, 28th and 29th January 2023",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Arjun Saxena",
          "number": "+91 95714 85158",
          "email": "20ucc021@lnmiit.ac.in",
        },
        {
          "name": "Divyanshi Gautam",
          "number": "+91 94624 21299",
          "email": "20ucs066@lnmiit.ac.in",
        },
        {
          "name": "Saumya Kalra",
          "number": "+91 6375 548121",
          "email": "20uec119@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1HCrqnCy_ya334RfaJEY5XRWwZ2VC5mpk/view?usp=share_link",
    "link": "",
    "clubemail": "debsoc@lnmiit.ac.in",
  },
  {
    "id": "14",
    "name": "Shark Tank",
    "club": "Startups",
    "participation": "Team Participation",
    "imgName": "./images/events/e-cell/sharktank/image.jpg",
    "poster": "/images/events/e-cell/sharktank/poster.png",
    "about": "A four-round competition that leads to the final stage of negotiations with the 'investor' in exchange for 'equity'. Scale-up your startup by earning mentorship and guidance by renowned Entrepreneurs from across the nation and established Angel Investors in this ecosystem.",
    "structure": "Round 1 (Online): Your startup's Pitch Deck needs to be Submitted on Unstop Platform ; Round 2 (Online): A video pitch describing your startup in the most creative form needs to be Submitted on Unstop Platform ; Round 3 (Offline): Offline Pitching in front of Judges (established Entrepreneurs); Round 4 (Offline): Final pitch in front of Angel Investors and Micro Venture Capitalists.",
    "prizes": "Cash Prizes worth a minimum of Rs. 1,00,000/- will be given to the winners including Prototype Funding of Rs.35,000+",
    "timeline": "Round 1 (Online): 14 December 2022 - 12 January 2023; Round 2 (Online): 13 Januray - 20 January 2023; Round 3 (Offline): 27th January 2023; Round 4 (Offline): 28th January 2023",
    "payment": 700,
    "contacts":
      [
        {
          "name": "Vaishvi Bansal",
          "number": "+91 80007 68730",
          "email": "20uec143@lnmiit.ac.in",
        },
        {
          "name": "Sarthak Kapoor",
          "number": "+91 63948 10829",
          "email": "20uec115@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1a2gUgb00k4zdFcPKsalunUtqlmIBGa3j/view?usp=share_link",
    "link": "https://unstop.com/competition/shark-tank-lnmiit-lnm-institute-of-information-technology-lnmiit-jaipur-522102",
    "clubemail": "ecell@lnmiit.ac.in",
  },
  {
    "id": "15",
    "name": "Virtual Stock Simulation",
    "club": "Startups",
    "participation": "Solo Participation",
    "imgName": "./images/events/e-cell/virtualstocksim/image.jpg",
    "poster": "/images/events/e-cell/virtualstocksim/poster.jpg",
    "about": "An online mode event where all the students will be provided a minimum virtual cash amount of 10 lakh Rupees and they will have the authoriy to use that amount and invest it in stocks and learn about the trading experience at the best possible way.",
    "structure": "The event would be happening on designated Stock Simulation Platform and the prize distribution ceremony would take place during Plinth ",
    "prizes": "Cash Prizes worth a minimum of Rs. 10,000/- will be given to the winners.",
    "timeline": "21 January 2023 - Registrations Closes, 23 January 2023 to 27 January 2023 - Contest dates",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Vaishvi Bansal",
          "number": "+91 80007 68730",
          "email": "20uec143@lnmiit.ac.in",
        },
        {
          "name": "Sarthak Kapoor",
          "number": "+91 63948 10829",
          "email": "20uec115@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1e6hYeltcu_kCMUJAsYvJSFs8hfhpnCya/view?usp=share_link",
    "link": "",
    "clubemail": "ecell@lnmiit.ac.in",
  },
  {
    "id": "25",
    "name": "RoboWar",
    "club": "Robotics",
    "club2": "LCRAI",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/robowars/image.jpg",
    "poster": "/images/events/phoenix/robowars/poster.png",
    "about": "A Competition in which robot battles using various methods to incapacitate the opponents robots.",
    "structure": "Points will be given by judges based on aggression, damage, and control. A team may win by knockout if it successfully immobilizes its opponent for 10 seconds. In case of a double KO, the winner will be decided by points.",
    "prizes": "1st Prize - ₹40000, 2nd Prize - ₹20000, Prizes worth ₹200000 ",
    "timeline": "28 JAN (2PM-5PM) & 29 JAN (3PM-6PM)",
    "payment": 1000,
    "contacts":
      [
        {
          "name": "Ayush sharma",
          "number": "+91 94602 57928",
          "email": "20ucc123@lnmiit.ac.in",
        },
        {
          "name": "Nanik Chaturvedi",
          "number": "+91 82093 93282",
          "email": "21ucc068@lnmiit.ac.in",
        },
        {
          "name": "Paras Jain",
          "number": "+91 75978 61350",
          "email": "21uec157@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1Gs4kwoEJO2toOT3BBFMS3t5s8tbzkkk0/view",
    "link": "https://forms.gle/EXPGAb3iy7TSem3f6",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "16",
    "name": "RoboRace",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/roborace/image.jpg",
    "poster": "/images/events/phoenix/roborace/poster.jpg",
    "about": "Teams have to build a bot which has to complete a custom-made race track with every obstacle one can think of.",
    "structure": "Team Size: 4-5 members. The team having less score than the top three teams will be eliminated and in the case of a tie in points, time taken will become the judging criteria for the affected teams",
    "prizes": "1st Prize - ₹15000, 2nd Prize - ₹10000, Prizes worth ₹40000  ",
    "timeline": "28 JAN (12PM-6PM) & 29 JAN (11AM-5PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Yash Pachauri",
          "number": "+91 81267 31140",
          "email": "20uec151@lnmiit.ac.in",
        },
        {
          "name": "Madhav Maheshwari",
          "number": "+91 89494 56930",
          "email": "20ucc061@lnmiit.ac.in",
        },
        {
          "name": "Yash R Khandelwal",
          "number": "+91 81075 20283",
          "email": "21ucs254@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1RLk1217JeAmx9tYWjsYF2c5pLNvzuXnR/view?usp=share_link",
    "link": "https://forms.gle/YV1tqYcZaUrJHKVJA",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "17",
    "name": "Robo Cup",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/robocup/image.png",
    "poster": "/images/events/phoenix/robocup/poster.jpg",
    "about": "Teams have to build two bots to score goals against each other while avoiding penalties. It will be a 2v2 match and the team scoring more goals wins.",
    "structure": "Team Size: 2 members. The team scoring more goals will be declared the winner. In the case of a tie, the winner is decided by the penalties that teams will be getting when: Kicking the ball out of the arena or damaging the opponent's bot, intentionally making physical contact with the opponent's bots, pulling the bot (in case of a wired connection).",
    "prizes": "Prizes worth ₹25000",
    "timeline": "27 JAN (12PM-6PM) & 28 JAN (3PM-6PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Nirnay Korde",
          "number": "+91 93266 64784",
          "email": "20ucs133@lnmiit.ac.in",
        },
        {
          "name": "Divyam Aggarwal",
          "number": "+91 70732 08666",
          "email": "21ucs071@lnmiit.ac.in",
        },
        {
          "name": "Divyansh Bansal",
          "number": "+91 63965 72084",
          "email": "20dec004@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/19nMcHPNy9mmHaB_6h5c8ONUuBm3P64JY/view?usp=share_link",
    "link": "https://forms.gle/zLw7LHRV62hgRi1C7",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "18",
    "name": "Transporter",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/transporter/image.jpg",
    "poster": "/images/events/phoenix/transporter/poster.png",
    "about": "Teams have to create a Bot with a grappling mechanism to complete the track and tasks including a maneuvering apparatus which can grab and drop elements",
    "structure": "Team Size: 2-6 members. If the dimensions of the bot are not as per the rulebook, the respective team will be eliminated",
    "prizes": "Prizes worth ₹35000",
    "timeline": "27 JAN (11AM-5PM) & 28 JAN (11AM-5PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Vaibhav Jaiswal",
          "number": "+91 75709 90685",
          "email": "20ucc126@lnmiit.ac.in",
        },
        {
          "name": "Lakshya Gupta",
          "number": "+91 78782 09385",
          "email": "20uec075@lnmiit.ac.in",
        },
        {
          "name": "Virender Kumar",
          "number": "+91 70116 98084",
          "email": "21uec144@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1f9czn_aGfLwwuw1BRYuLkgIiolPcb4A5/view?usp=share_link",
    "link": "https://forms.gle/vEAZzMA6qJVKaEdh9",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "19",
    "name": "Nitro Race",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/nitrorace/image.jpg",
    "poster": "/images/events/phoenix/nitrorace/poster.jpg",
    "about": "A specially designed off-road dirt track where teams will race against each other with their remote-controlled IC engine cars and win amazing cash prizes and vouchers",
    "structure": "Team Size: 2-6 members. If a car is disintegrated during the race or there is another car that has completed the laps in much lesser time or a car starts off twice before waving the flag or countdown, the team is eliminated.",
    "prizes": "1st Prize - ₹14000, 2nd Prize - ₹6000, Prizes worth ₹40000 ",
    "timeline": "28 JAN (12PM-4PM)",
    "contacts":
      [
        {
          "name": "Vivek Kumar",
          "number": "+91 88241 43775",
          "email": "20ume050@lnmiit.ac.in",
        },
        {
          "name": "Raj Kansagra",
          "number": "+91 70966 87004",
          "email": "21ucc080@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1m5wO5JcpHDDnvTxiSJujsj4Oaw1TdSRP/view?usp=share_link",
    "link": "https://forms.gle/buZAnQZ6zDFGUui1A",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "20",
    "name": "Drone",
    "club2": "ASME",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/drone/image.jpg",
    "poster": "/images/events/phoenix/drone/poster.jpg",
    "about": "Teams have  to design and build a multirotor racing drone to maneuver through obstacles and elements present on the racing track in minimum time possible without crashing.",
    "structure": "Team Size: 1-4 members. There will be no elimination rounds. The team with the minimum time run will be considered as the winner.",
    "prizes": "Prizes worth ₹40000  ",
    "timeline": "28 JAN (5PM-8PM) & 29 JAN (5PM-8PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Akshat Jangid",
          "number": "+91 81072 18401",
          "email": "20ume005@lnmiit.ac.in",
        },
        {
          "name": "Lakshya Choudhary",
          "number": "+91 62802 05416",
          "email": "20uec074@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1qElpcELcWc3yulSM9mKzVk1SqDsTvuIo/view?usp=drivesdk",
    "link": "https://forms.gle/hCamdpQVUMvgvsWs9",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "21",
    "name": "RC Plane",
    "club": "Robotics",
    "club2": "ASME",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/rcplane/image.png",
    "poster": "/images/events/phoenix/rcplane/poster.png",
    "about": "Teams have to build a RC Plane which is aerodynamically sound and within the specified dimensions to achieve a successful flight",
    "structure": "",
    "prizes": "Prizes worth ₹20000  ",
    "timeline": "29 JAN (10AM-4PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Rudransh Sharma",
          "number": "+91 95991 35384",
          "email": "20ume043@lnmiit.ac.in",
        },
        {
          "name": "Lakshay Setia",
          "number": "+91 89684 42211",
          "email": "20ucs105@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1eC2LhPSJei2WhpYDNCmleCQz0-jlCGCq/view",
    "link": "https://forms.gle/MzLsvoSmBcvHRHwcA",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "22",
    "name": "Moto Boat",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/motoboat/image.png",
    "poster": "/images/events/phoenix/motoboat/poster.png",
    "about": "Team has to build a RC boat to complete the aquatic obstacle course",
    "structure": "Team Size: 1-4 members. If the dimensions of the bot are not as per the rulebook, if the bot gets disintegrated during the event, or if the team has scored fewer points than other teams, then the respective team will be eliminated.",
    "prizes": "Prizes worth ₹20000",
    "timeline": "27 JAN (12PM-3PM) & 28 JAN (12PM-3PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Shrey Parikh",
          "number": "+91 82001 18125",
          "email": "20ucs185@lnmiit.ac.in",
        },
        {
          "name": "Siddharth Chaudhary",
          "number": "+91 70529 60505",
          "email": "20dcs010@lnmiit.ac.in",
        },
        {
          "name": "Aditi Agrawal",
          "number": "+91 70165 52604",
          "email": "21ucs006@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1oL5iR0SIrQ55DwzWIcDiTpH2E6YWL5hZ/view?usp=share_link",
    "link": "https://forms.gle/wcxeUFAA9NeX6h9E9",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "23",
    "name": "Exhibition",
    "club": "Robotics",
    "club2": "ASME",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/exhibition/image.png",
    "poster": "/images/events/phoenix/exhibition/poster.png",
    "about": "",
    "structure": "",
    "prizes": "1st Prize - ₹10000, 2nd Prize - ₹5000",
    "timeline": "29 JAN (11AM-4PM) ",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Prajwal chittora",
          "number": "+91 63679 81595",
          "email": "20uec093@lnmiit.ac.in",
        },
        {
          "name": "Lakshay Setia",
          "number": "+91 89684 42211",
          "email": "20ucs105@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "https://forms.gle/4qkCrjyGLKAWBwwR8",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "26",
    "name": "Squid Game",
    "club": "Robotics",
    "participation": "Solo Participation",
    "imgName": "./images/events/phoenix/squidgame/image.png",
    "poster": "/images/events/phoenix/squidgame/poster.png",
    "about": "Real Life Squid game where you have to tread your path cautiously and cross the finish line in order to both, survive and win amazing prizes.",
    "structure": "Once your balloon is shot, you will be considered eliminated.",
    "prizes": " Gift hampers ",
    "timeline": "28 JAN & 29 JAN",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Yash Pachauri",
          "number": "+91 81267 31140",
          "email": "20uec151@lnmiit.ac.in",
        },
        {
          "name": "Aishnee Porwal",
          "number": "+91 81188 21681",
          "email": "20ucs012@lnmiit.ac.in",
        },
        {
          "name": "Saransh Kathal",
          "number": "+91 7000677600",
          "email": "21uec120@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1hN6TBXX6ZNiLWlZwjb149bmqKl_X_MYP/view?usp=share_link",
    "link": "",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "27",
    "name": "Maze Solver",
    "club": "Robotics",
    "participation": "Team Participation",
    "imgName": "./images/events/phoenix/mazesolver/image.png",
    "poster": "/images/events/phoenix/mazesolver/poster.jpg",
    "about": "Teams must create an autonomous robot that can navigate a maze by following a black line and keeping track of directions.The bot must navigate the maze from starting to ending point in the shortest amount of time while analysing the course during the dry run.",
    "structure": "Team Size: 1-4 members. Only one member is allowed to handle the bot, other than that personal devices are not permitted close to the arena, and all other Wi-Fi, Bluetooth, and other devices need to be turned off only a bot should be inside the arena, nothing else.",
    "prizes": "Prizes worth ₹30000 ",
    "timeline": "28 JAN (11AM-6PM)",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Lakshya Choudhary",
          "number": "+91 62802 05416",
          "email": "20uec074@lnmiit.ac.in",
        },
        {
          "name": "Prajwal Chittora",
          "number": "+91 63679 81595",
          "email": "20uec093@lnmiit.ac.in",
        },
        {
          "name": "Smit Patel",
          "number": "+91 72328 77112",
          "email": "21ucs205@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1myh6pyjT54wRcrUc1tNizTtpnRXcbIOE/view?usp=share_link",
    "link": "https://forms.gle/X2FRgQtvnX1mi2cW6",
    "clubemail": "phoenixclub@lnmiit.ac.in",
  },
  {
    "id": "28",
    "name": "Brandwagon",
    "club": "Quizzinga",
    "participation": "Team Participation ",
    "imgName": "./images/events/quizzinga/brandwagon/image.jpeg",
    "poster": "/images/events/quizzinga/brandwagon/poster.jpeg",
    "about": "Brandwagon is Quizzinga's flagship business quiz which takes place every year during Plinth. It will be held in two rounds. First is the written round and six highest scoring teams will move on to the finals.You have to participate in teams of 3.",
    "structure": "Team Size: 3 members. Prelims: Pen-paper based round. The quizmaster will present the questions and you will have to write your answers. Final round: Top 6 teams will compete in a quiz consisting of different biz genres to become the champion. ",
    "prizes": "Prizes worth Rs. 15,000",
    "timeline": "Date: 28.01.2023 Time: Starts at 10 AM",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Aditya Singh",
          "number": "+91 82109 33558",
          "email": "20uec008@lnmiit.ac.in",
        },
        {
          "name": "Md. Raiyan Athar",
          "number": "+91 82101 49662",
          "email": "20ume027@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1WGAFtOho72M649xFUlAwNa-clklOdQRw/view?src/components/Competitions/Competitions.jsusp=share_link",
    "link": "https://forms.gle/EA3rhaQ6Dcg6XHV48",
    "clubemail": "quizzinga@lnmiit.ac.in",
  },
  {
    "id": "29",
    "name": "Cryptex",
    "club": "Quizzinga",
    "participation": "Solo Participation ",
    "imgName": "./images/events/quizzinga/cryptex/image.jpeg",
    "poster": "/images/events/quizzinga/cryptex/poster.jpg",
    "about": "Cryptex is an online quiz competition with a format similar to a treasure hunt. Each participant has to register individually and go through all the levels before being crowned as the winner. The questions will be diverse and will include all forms of genres. Questions will be posted on Plinth’s website and hints will be posted on instagram stories of @quizzingalnm.",
    "structure": "Questions will be displayed in a sequential manner. The answer to a queston is the key to unlock the next question. We will post hints on our Instagram stories (@quizzingalnm). The first few participants to unlock all the levels will be declared the winners.",
    "prizes": "Prizes worth Rs. 10,000",
    "timeline": "Date : 20.01.2023 to 22.01.2023",
    "payment": 0,
    "contacts":
      [
        {
          "name": "Aditya Singh",
          "number": "+91 82109 33558",
          "email": "20uec008@lnmiit.ac.in",
        },
        {
          "name": "Md. Raiyan Athar",
          "number": "+91 82101 49662",
          "email": "20ume027@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1PjImrYlW7aTxIj_tAVNXrUkTf8PLckUO/view",
    "link": "https://unstop.com/quiz/cryptex-lnm-institute-of-information-technology-lnmiit-jaipur-582136",
    "clubemail": "quizzinga@lnmiit.ac.in",
  },
  {
    "id": "30",
    "name": "IPL-Auction",
    "club": "Quizzinga",
    "participation": "Team Participation ",
    "imgName": "./images/events/quizzinga/ipl-auction/image.jpeg",
    "poster": "/images/events/quizzinga/ipl-auction/poster.jpeg",
    "about": "IPL Auction is a real life simulation of the auction which we witness before every IPL season. It will be held in two rounds. First will be a cricket quiz and second round will be an auction between the shortlisted teams based on their first round scores. The aim will be maximizing rating given a fixed purse. You have to participate in teams of 3.",
    "structure": "Team Size: 3 members. Prelims: Pen-paper based round. The quizmaster will present the questions and you will have to write your answers.  Final Round: Top 16 teams will qualify for this round. We will merge two teams into one and then they will be alloted different IPL franchises. The 8 franchises will compete against each other to maximise their rating given a pixed 100 Cr. purse. ",
    "prizes": "Prizes worth Rs. 20,000",
    "timeline": "Date: 29.01.2023  Time: 10:00 AM-12:00 PM Prelims  01:00 PM-06:00 PM Auction",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Aditya Singh",
          "number": "+91 82109 33558",
          "email": "20uec008@lnmiit.ac.in",
        },
        {
          "name": "Md. Raiyan Athar",
          "number": "+91 82101 49662",
          "email": "20ume027@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1TTiCsoS8TB14Y4Ek-vHeyOT_Nekv00nC/view?usp=share_link",
    "link": "https://forms.gle/8JErBs3W2rh9ErDr8",
    "clubemail": "quizzinga@lnmiit.ac.in",
  },
  {
    "id": "31",
    "name": "BloodConnect",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "BloodConnect is India’s largest youth-led organization that works with colleges, corporates, and RWAs to help the blood banks be blood sufficient. In collaboration with PLINTH'23 we are providing camps to contribute for the good cause. We at BloodConnect live by the motto of saving lives by ensuring every drop of blood contributes towards the right cause of saving lives.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Shivam Yadav",
          "number": "+91 63888 09962",
          "email": "20uec121@lnmiit.ac.in",
        },
        {
          "name": "Arin Khandelwal",
          "number": "+91 70963 56002",
          "email": "21ucs027@lnmiit.ac.in",
        },
        {
          "name": "Bhavika Agarwal",
          "number": "+91 98293 00345",
          "email": "20dec003@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "32",
    "name": "WCA SPEEDCUBING",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "Speedcubing is a competitive sport involving sovling a variety of combination puzzles using cube. The World Cube Associatin (WCA) governs competitions for mechanical puzzles called 'twisty puzzles'. PLINTH'23 is a stage to participate and show case your skills.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 400,
    "contacts":
      [
        {
          "name": "Arnav Arora",
          "number": "+91 88264 00501",
          "email": "20ucs026@lnmiit.ac.in",
        },
        {
          "name": "Akash Mondal",
          "number": "",
          "email": "20ucs013@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "33",
    "name": "MONOPOLY LNMIIT EDITION",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "A fun version of monopoly which will help everyone to connect to LNMIIT's culture and college life.",
    "structure": "2-4 players will play at one time",
    "prizes": "",
    "timeline": "11AM to 5PM on January 27th, 2023",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Yash Pachauri",
          "number": "+91 81267 31140",
          "email": "20uec151@lnmiit.ac.in",
        },
        {
          "name": "Maanas Gupta",
          "number": "+91 73183 74333",
          "email": "21ucs120@lnmiit.ac.in",
        },
        {
          "name": "Tushar Agarwal",
          "number": "+91 99549 55765",
          "email": "21ume055@lnmiit.ac.in",
        },
      ],
    "rulebook": "https://drive.google.com/file/d/1XH9chIcE8kj9EzU0L4KWWu1uVVnG5Lpw/view?usp=drivesdk",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "34",
    "name": "WHO DUN IT!",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "A real time crime scene is created that needs to be observed by the participants and then solve the mystery lying ahead.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Siddharth Chaudhary",
          "number": "+91 70529 60505",
          "email": "20dcs010@lnmiit.ac.in",
        },
        {
          "name": "Khushi Mittal",
          "number": "+91 89059 59063",
          "email": "21ume025@lnmiit.ac.in",
        },
        {
          "name": "Mupparapu Sricharan",
          "number": "+91 85008 75880",
          "email": "21ume032@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "35",
    "name": "Virtual Dive",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "Lose yourself in virtual reality. In this fun event you can enjoy the VR along with your companions.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Bhavya Gupta",
          "number": "+91 70090 45151",
          "email": "20ucs052@lnmiit.ac.in",
        },
        {
          "name": "Ansh Pant",
          "number": "+91 85959 86243",
          "email": "20ucs023@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "36",
    "name": "Paint Ball",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "Better than a  multiplayer battle royale. Hone your shooting skills to excel in this team shooting arena full of \"paint-balls\".",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Saransh Jindal",
          "number": "+91 88516 25921",
          "email": "20uec112@lnmiit.ac.in",
        },
        {
          "name": "Siddharth Chaudhary",
          "number": "+91 70529 60505",
          "email": "20dcs010@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "37",
    "name": "Ad Selfie",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Gautam Mittal",
          "number": "+91 70785 13565",
          "email": "21ucs081@lnmiit.ac.in",
        },
        {
          "name": "Ansh Pant",
          "number": "+91 85959 86243",
          "email": "20ucs023@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "38",
    "name": "Game Zone",
    "club": "Fun Events",
    "participation": "Solo Participation",
    "imgName": "",
    "poster": "",
    "about": "Dive into the meta-verse of the game zone. Jump into the excitement-zone with your friends.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Sahil Gupta",
          "number": "+91 70158 24452",
          "email": "20ucs166@lnmiit.ac.in",
        },
        {
          "name": "Chitransh Jaiswal",
          "number": "+91 74259 20696",
          "email": "20ucs059@lnmiit.ac.in",
        }
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "39",
    "name": "Web3 Gaming hours",
    "club": "Web3",
    "participation": "Team Participation",
    "imgName": "",
    "poster": "",
    "about": "Web3 gaming is here to revolutionise the way we think about gaming forever. With the power of blockchain technology at its fingertips, web3 gaming allows for the creation of decentralised, transparent, and secure platforms that will change the industry as we know it. Plinth brings an exciting opportunity to learn about web3 gaming through workshops and sessions with the industry leaders.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Vinay Sharma",
          "number": "+91 95491 78651",
          "email": "19ume011@lnmiit.ac.in",
        },
        {
          "name": "Meet Patel",
          "number": "+91 70418 13479",
          "email": "19ume020@lnmiit.ac.in",
        }
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "40",
    "name": "DeFi hours",
    "club": "Web3",
    "participation": "Team Participation",
    "imgName": "",
    "poster": "",
    "about": "Gone are the days of traditional financial institutions holding all the power. DeFi puts the control back in the hands of the people, allowing them to access financial services without the need for intermediaries.2023 is going to be the year for DeFi mass adoption and we don’t want you to get behind. Listen to some of the biggest names from DeFi India in Plinth.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Vinay Sharma",
          "number": "+91 95491 78651",
          "email": "19ume011@lnmiit.ac.in",
        },
        {
          "name": "Meet Patel",
          "number": "+91 70418 13479",
          "email": "19ume020@lnmiit.ac.in",
        }
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "41",
    "name": "Multichain panel discussion",
    "club": "Web3",
    "participation": "Team Participation",
    "imgName": "",
    "poster": "",
    "about": "Multichain panel discussion of having to choose between different blockchain platforms - with multichain, you can have it all. Interoperability is at the heart of multichain, allowing different blockchain networks to communicate and work together seamlessly. But the benefits of multichain go beyond just interoperability. Learn about the future of Blockchain tech with the panel of most amazing speakers from industry.",
    "structure": "",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Vinay Sharma",
          "number": "+91 95491 78651",
          "email": "19ume011@lnmiit.ac.in",
        },
        {
          "name": "Meet Patel",
          "number": "+91 70418 13479",
          "email": "19ume020@lnmiit.ac.in",
        }
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "",
  },
  {
    "id": "42",
    "name": "Bridge the Barrier",
    "club": "ASME",
    "participation": "Team Participation",
    "imgName": "./images/events/asme/bridgethebarrier/poster.jpg",
    "poster": "/images/events/asme/bridgethebarrier/poster.jpg",
    "about": "You have to team up together and find a innovative way of joining two masses of land together so that people and traffic and move around. Design a bridge that can sustain a specific amount of load and win exciting prizes",
    "structure": "Team Size: 3-5 people",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Krishna Kulshreshtha",
          "number": "+91 80769 63691",
          "email": "20ume022@lnmiit.ac.in",
        },
        {
          "name": "Raj Krishna",
          "number": "+91 93364 23032",
          "email": "21ume041@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "asme@lnmiit.ac.in",
  },
  {
    "id": "43",
    "name": "Model Rocket Masters",
    "club": "ASME",
    "participation": "Team Participation",
    "imgName": "./images/events/asme/modelrocketmasters/poster.jpg",
    "poster": "/images/events/asme/modelrocketmasters/poster.jpg",
    "about": "Design and build a model rocket within the specified dimensions robust enough to withstand the pressure with the solid rocket motor provided by the organizers and when launched from the launch pad achieves the maximum altitude above ground level.",
    "structure": "Team Size: 3-5 people",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Krishna Kulshreshtha",
          "number": "+91 80769 63691",
          "email": "20ume022@lnmiit.ac.in",
        },
        {
          "name": "Aviral Shukla",
          "number": "+91 75991 07769",
          "email": "21ucs043@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "asme@lnmiit.ac.in",
  },
  {
    "id": "44",
    "name": "Spaghetti Tower",
    "club": "ASME",
    "participation": "Team Participation",
    "imgName": "./images/events/asme/sphaghettitower/poster.jpg",
    "poster": "/images/events/asme/sphaghettitower/poster.jpg",
    "about": "It’s a fun event that will last upto 20 to 25 mins. The basic idea is that a team is given a handful of supplies to work with spaghetti, marshmallow, tape and string.",
    "structure": "Team SIze: 1-3 people",
    "prizes": "",
    "timeline": "",
    "payment": 99,
    "contacts":
      [
        {
          "name": "Krishna Kulshreshtha",
          "number": "+91 80769 63691",
          "email": "20ume022@lnmiit.ac.in",
        },
        {
          "name": "Kavya Singhal",
          "number": "+91 78775 24323",
          "email": "21ume022@lnmiit.ac.in",
        },
      ],
    "rulebook": "",
    "link": "",
    "clubemail": "asme@lnmiit.ac.in",
  },

];
