import { Fragment } from "react";
import React from "react";
export const teams = [
  {
    team: "Fest Heads",
    leads: [
      {
        name: "Gunit Varshney",
        image: "./images/teams/fest_heads/gunitY19.jfif",
        designation: "Fest Head",
        phone: "+91 88755 10652",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Raja Kumar Singh",
        image: "./images/teams/fest_heads/raja.jpg",
        designation: "Fest Head",
        phone: "+91 96803 72941",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
    ],
    members: [],
  },
  
  {
    team: "Council Members",
    leads: [
      {
        name: "Ayush Sharma",
        image: "./images/teams/council_members/sharma.jpg",
        designation: "General Secretary",
        phone: "+91 94602 57928",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Muskan Singla",
        image: "./images/teams/council_members/muskan.jpg",
        designation: "As. General Secretary",
        phone: "+91 83770 89610",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Dev Gupta",
        image: "./images/teams/council_members/dev.jpg",
        designation: "Finance Convener",
        phone: "+91 77289 70727",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
    ],
    members: [],
  },
  {
    team: "Tech Team",
    leads: [
      {
        name: "Ketan Jakhar",
        image: "./images/teams/tech_team/ketan.jpg",
        designation: "Tech Lead",
        phone: "+91 94617 21651",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Kingshuk Ghosh",
        image: "./images/teams/tech_team/kingshuk.jpg",
        designation: "Tech Sub-Lead",
        phone: "+91 93216 67834",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
      {
        name: "Sourabh Joshi",
        image: "./images/teams/tech_team/sourabh.jpeg",
        designation: "Tech Sub-Lead",
        phone: "+91 95494 08165",
        mail: "/",
        facebook: "/",
        instagram: "/",
        linkedin: "/",
      },
    ],
    members: [
      {
        subteam: "Designers & Developers",
        members: [
          {
            name: "Aditya Mittal",
            image: "./images/teams/tech_team/mittal.jpg",
            designation: "Design Mentor",
            phone: "+91 84400 74101",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
          {
            name: "Aryan Bansal",
            image: "./images/teams/tech_team/aryan-bansal.jpg",
            designation: "UI/UX Designer",
            phone: "+91 93510 36367",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
          {
            name: "Vishal Kumar",
            image: "./images/teams/tech_team/vishal.jpg",
            designation: <Fragment>Frontend Developer<br/>UI/UX Designer</Fragment>,
            phone: "+91 92057 34004",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
          {
            name: "Aryan Gupta",
            image: "./images/teams/tech_team/aryan-gupta.jpg",
            designation: "Frontend Developer",
            phone: "+91 90642 80911",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
          {
            name: "Ayush Mathpal",
            image: "./images/teams/tech_team/ayush.jpg",
            designation: "Frontend Developer",
            phone: "+91 90136 66250",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
          {
            name: "Arnit Gupta",
            image: "./images/teams/tech_team/arnit.jpg",
            designation: "Backend Developer",
            phone: "+91 6367 880 107",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
          {
            name: "Ashutosh Jha",
            image: "./images/teams/tech_team/ashutosh.jpg",
            designation: "Backend Developer",
            phone: "+91 93284 09963",
            mail: "/",
            facebook: "/",
            instagram: "/",
            linkedin: "/",
          },
        ],
      },
      
    ],
  },
];