import { Fragment } from "react";
import React from "react";
export const teams = [
  {
    team: "Fest Heads",
    leads: [
      {
        name: "Gunit Varshney",
        image: "./images/teams/fest_heads/gunitY19.jfif",
        designation: "Fest Head",
        phone: "+91 88755 10652",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
      {
        name: "Raja Kumar Singh",
        image: "./images/teams/fest_heads/raja.jpg",
        designation: "Fest Head",
        phone: "+91 96803 72941",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
    ],
    members: [],
  },
  
  {
    team: "Council Members",
    leads: [
      {
        name: "Ayush Sharma",
        image: "./images/teams/council_members/sharma.jpg",
        designation: "General Secretary",
        phone: "+91 94602 57928",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
      {
        name: "Muskan Singla",
        image: "./images/teams/council_members/muskan.jpg",
        designation: "As. General Secretary",
        phone: "+91 83770 89610",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
      {
        name: "Dev Gupta",
        image: "./images/teams/council_members/dev.jpg",
        designation: "Finance Convener",
        phone: "+91 77289 70727",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
    ],
    members: [],
  },
  {
    team: "Web3 Team",
    leads: [
      {
        name: "Vinay Sharma",
        image: "./images/teams/web3/Vinay.png",
        designation: "Web3 Lead",
        phone: "+91 95491 78651",
        mail: "vinaystwt@gmail.com ",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "https://www.linkedin.com/in/vinay-sharma-263553166/",
      },
    ],
    members: [
      {
        subteam: "Members",
        members: [
          {
            name: "Bhavyam Arora",
            image: "./images/teams/web3/bhavyam.jpg",
            designation: "Website and Brochure",
            phone: "+91 96804 51574",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Sajal Sharma",
            image: "./images/teams/web3/sajal.png",
            designation: "Website and Brochure",
            phone: "+91 80056 50361",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Nihar Thummar",
            image: "./images/teams/web3/nihar.jpg",
            designation: "Events and Operations",
            phone: "+91 84697 60423",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Meet Patel",
            image: "./images/teams/web3/meet.jpg",
            designation: "Events and Operations",
            phone: "+91 70418 13479",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Aditya Mittal",
            image: "./images/teams/web3/aditya.jpg",
            designation: "Events and Operations",
            phone: "+91 94608 44812",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Advik Singhania",
            image: "./images/teams/web3/advik.jpg",
            designation: "Events and Operations",
            phone: "+91 90496 19607",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Ashu Gupta",
            image: "./images/teams/web3/ashu.jpg",
            designation: "Design and Operations",
            phone: "+91 94140 42468",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/thisisashugupta/",
            linkedin: "https://www.linkedin.com/in/thisisashugupta/",
          },
        ],
      },
    ],
  },
  {
    team: "Tech Team",
    leads: [
      {
        name: "Ketan Jakhar",
        image: "./images/teams/tech_team/ketan.jpg",
        designation: "Tech Lead",
        phone: "+91 94617 21651",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
        batch: "senior",
      },
      {
        name: "Kingshuk Ghosh",
        image: "./images/teams/tech_team/kingshuk.jpg",
        designation: "Tech Sub-Lead",
        phone: "+91 93216 67834",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
        batch: "senior",
      },
      {
        name: "Sourabh Joshi",
        image: "./images/teams/tech_team/sourabh.jpeg",
        designation: "Tech Sub-Lead",
        phone: "+91 95494 08165",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
        batch: "senior",
      },
    ],
    members: [
      {
        subteam: "Designers & Developers",
        members: [
          {
            name: "Aditya Mittal",
            image: "./images/teams/tech_team/mittal.jpg",
            designation: "Design Mentor",
            phone: "+91 84400 74101",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
            batch: "senior",

          },
          {
            name: "Aryan Bansal",
            image: "./images/teams/tech_team/aryan-bansal.jpg",
            designation: "UI/UX Designer",
            phone: "+91 93510 36367",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
            batch: "junior",
          },
          {
            name: "Vishal Kumar",
            image: "./images/teams/tech_team/vishal.jpg",
            designation: <Fragment>Frontend Developer<br/>UI/UX Designer</Fragment>,
            phone: "+91 92057 34004",
            mail: "https://mail.google.com/mail/?view=cm&fs=1&to=21ucc116@lnmiit.ac.in",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/vishal.kr4004/",
            linkedin: "https://www.linkedin.com/in/v15h4l/",
            batch: "junior",
          },
          {
            name: "Aryan Gupta",
            image: "./images/teams/tech_team/aryan-gupta.jpg",
            designation: "Frontend Developer",
            phone: "+91 90642 80911",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
            batch: "junior",
          },
          {
            name: "Ayush Mathpal",
            image: "./images/teams/tech_team/ayush.jpg",
            designation: "Frontend Developer",
            phone: "+91 90136 66250",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
            batch: "junior",
          },
          {
            name: "Arnit Gupta",
            image: "./images/teams/tech_team/arnit.jpg",
            designation: "Backend Developer",
            phone: "+91 6367 880 107",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
            batch: "junior",
          },
          {
            name: "Ashutosh Jha",
            image: "./images/teams/tech_team/ashutosh.jpg",
            designation: "Backend Developer",
            phone: "+91 93284 09963",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
            batch: "junior",
          },
        ],
      },
      
    ],
  },
  {
    team: "Content Team",
    leads: [
      {
        name: "Krishna Kulshreshtha",
        image: "./images/teams/content_team/krishna.jpeg",
        designation: "Content Lead",
        phone: "+91 80769 63691",
        mail: "kkulshreshtha29@gmail.com",
        facebook: "/ourteam",
        instagram: "https://www.instagram.com/kaun_kanha/",
        linkedin: "https://www.linkedin.com/in/krishna-kulshreshtha-687268221/",
      },
      {
        name: "Arjun Saxena",
        image: "./images/teams/content_team/arjun.jpg",
        designation: "Content Group Lead",
        phone: "+91 9571485158",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "https://www.linkedin.com/in/arjun-saxena-497029165/",
      },
    ],
    members: [
      {
        subteam: "Team Executive",
        members: [
          {
            name: "Deshna Thakur",
            image: "./images/teams/content_team/deshna.jpg",
            designation: "Content Team Executive",
            phone: "+91 7339899087",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Medhansh Sharma",
            image: "./images/teams/content_team/medhansh.jpg",
            designation: "Content Team Executive",
            phone: "+91 8209516918",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Diya Ghodasara",
            image: "./images/teams/content_team/diya.jpg",
            designation: "Content Team Executive",
            phone: "+91 9510326120",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Ayan Farooqui",
            image: "./images/teams/content_team/ayan.jpg",
            designation: "Content Team Executive",
            phone: "+91 7376640490",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Pranav Agarwal",
            image: "./images/teams/content_team/pranav.jpg",
            designation: "Content Team Executive",
            phone: "+91 9106177115",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
        ],
      }, 
    ],
  },
  {
    team: "Design Team",
    leads: [
      {
        name: "Anuj Goyal",
        image: "./images/teams/design_team/anuj.jpeg",
        designation: "Design Head",
        phone: "",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
      {
        name: "Harshita Ghatiya",
        image: "./images/teams/design_team/harshita.jpg",
        designation: "Design Head",
        phone: "+91 99932 27261",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "https://www.linkedin.com/in/harshita-ghatiya-818658243",
      },
      {
        name: "Rudransh Sharma",
        image: "./images/teams/design_team/rudransh.JPG",
        designation: "Design Head",
        phone: "",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
      {
        name: "Ashu Gupta",
        image: "./images/teams/design_team/ashu.jpg",
        designation: "Video Editing Lead ",
        phone: "+91 94140 42468",
        mail: "ashugpt1812@gmail.com",
        facebook: "/ourteam",
        instagram: "https://www.instagram.com/thisisashugupta/",
        linkedin: "https://www.linkedin.com/in/thisisashugupta/",
      },
    ],
    members: [
      {
        subteam: "Graphic Designers & Video Editors",
        members: [
          {
            name: "Gungun Hinduja",
            image: "./images/teams/design_team/gungun.jpg",
            designation: "Graphic Designer ",
            phone: "",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Aditya Narang",
            image: "./images/teams/design_team/aditya.jpg",
            designation: "Graphic Designer",
            phone: "",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Anwesh Mohanty",
            image: "./images/teams/design_team/anwesh.jpg",
            designation: "Video Editor",
            phone: "+91 72979 26874",
            mail: "21uec029@lnmiit.ac.in",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/ig.anweshh/",
            linkedin: "https://www.linkedin.com/in/anwesh-k-mohanty-097242223/",
          },
          {
            name: "Vuuren Mohanty",
            image: "./images/teams/design_team/vuuren.jpg",
            designation: "Video Editor",
            phone: "+91 99971 16303",
            mail: "21uec043@lnmiit.ac.in",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/raulmohanty/",
            linkedin: "https://www.linkedin.com/in/vuuren-mohanty-29b999223",
          },
          {
            name: "Priyanshu Jain",
            image: "./images/teams/design_team/priyanshu.jpg",
            designation: "Video Editor",
            phone: "+91 93583 02434",
            mail: "21ucs162@lnmiit.ac.in",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/priyanshu_4803/",
            linkedin: "https://www.linkedin.com/in/priyanshu-jain-503170249",
          },
          {
            name: "Pushpak Jha",
            image: "./images/teams/design_team/pushpak.jpg",
            designation: "Video Editor",
            phone: "+91 96549 65888",
            mail: "jha.pushpak78g@gmail.com",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/pushpak.peace/",
            linkedin: "https://www.linkedin.com/in/pushpak-kumar-jha-963192243",
          },
        ],
      },
    ],
  },
  {
    team: "Social Media Team",
    leads: [
      {
        name: "Premansh Sharma",
        image: "./images/teams/social_media/premansh.JPG",
        designation: "Social Media Lead",
        phone: "+91 89491 63041 ",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
      {
        name: "Kingshuk Ghosh",
        image: "./images/teams/tech_team/kingshuk.jpg",
        designation: "Social Media Lead",
        phone: "+91 93216 67834",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
    ],
    members: [
      {
        subteam: "Members",
        members: [
          {
            name: "Manas Sharma",
            image: "./images/teams/social_media/manas.jpg",
            designation: "Instagram/Twitter/YT Handler",
            phone: "+91 86198 89016",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Gautam Mittal",
            image: "./images/teams/social_media/gautum.jpg",
            designation: "Linkedin/Facebook/YT Handler",
            phone: "+91 70785 13565",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
        ],
      },
    ],
  },
  {
    team: "PR Team",
    leads: [
      {
        name: "Arjun Saxena",
        image: "./images/teams/pr_team/arjun.jpg",
        designation: "Team Lead",
        phone: "+91 95714 85158",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "https://instagram.com/krishna_s_arjun?igshid=Yzg5MTU1MDY=",
        linkedin: "https://www.linkedin.com/in/arjun-saxena-497029165",
      },
      {
        name: "Muskan Singla",
        image: "./images/teams/council_members/muskan.jpg",
        designation: "Team Lead",
        phone: "+91 83770 89610",
        mail: "/ourteam",
        facebook: "/ourteam",
        instagram: "https://instagram.com/muskan_singla1801?igshid=Yzg5MTU1MDY=",
        linkedin: "https://www.linkedin.com/in/muskan-singla-8632521bb",
      },
    ],
    members: [
      {
        subteam: "PR Group Leads & Members",
        members: [
          {
            name: "Iresh Agrawal",
            image: "./images/teams/pr_team/iresh.jpg",
            designation: "Group Lead",
            phone: "+91 8791616879",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/ireshagrawal/",
            linkedin: "https://www.linkedin.com/in/iresh-agrawal-859927206/",
          },
          {
            name: "Krishna Kulshreshtha",
            image: "./images/teams/pr_team/krishna.jpg",
            designation: "Group Lead",
            phone: "+91 8076963691",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/kaun_kanha/",
            linkedin: "https://www.linkedin.com/in/krishna-kulshreshtha-687268221/",
          },
          {
            name: "Vansh Gupta",
            image: "./images/teams/pr_team/vansh.jpg",
            designation: "Group Lead",
            phone: "+91 9462860600",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/vg_vansh/",
            linkedin: "https://www.linkedin.com/in/vansh-gupta-1bb543200",
          },
          {
            name: "Yash Gaur",
            image: "./images/teams/pr_team/yash_gaur.jpg",
            designation: "Group Lead",
            phone: "+91 9807018491",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://instagram.com/yashg_5311?igshid=ZmZhODViOGI=",
            linkedin: "https://www.linkedin.com/in/yash-gaur-946675223",
          },
          {
            name: "Yash Pachauri",
            image: "./images/teams/pr_team/yash_pachauri.jpg",
            designation: "Group Lead",
            phone: "+91 8126731140",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/yashpachauri_/",
            linkedin: "https://www.linkedin.com/in/yash-pachauri-209332161/",
          },
          {
            name: "Aryan Bansal",
            image: "./images/teams/tech_team/aryan-bansal.jpg",
            designation: "Team Executive",
            phone: "+91 9351036367",
            mail: "aryan.bansal0274@gmail.com",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/aryan_bansal02/",
            linkedin: "https://www.linkedin.com/in/aryan-bansal02",
          },
          {
            name: "Jay Jashanani",
            image: "./images/teams/pr_team/jay.jpg",
            designation: "Team Executive",
            phone: "+91 7021677600",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://instagram.com/jashnanijay",
            linkedin: "https://www.linkedin.com/in/jay-jashnani-6a066a219",
          },
          {
            name: "Kaushtubh Agrawal",
            image: "./images/teams/pr_team/kaushtubh.jpg",
            designation: "Team Executive",
            phone: "+91 7607220062",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Labhesh Mundhada",
            image: "./images/teams/pr_team/labesh.jpg",
            designation: "Team Executive",
            phone: "+91 9307192403",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://instagram.com/incriwer_boy?igshid=Yzg5MTU1MDY=",
            linkedin: "https://www.linkedin.com/in/labhesh-mundhada-a25921227",
          },
          {
            name: "Pranav Agarwal",
            image: "./images/teams/pr_team/pranav.jpg",
            designation: "Team Executive",
            phone: "+91 9106177115",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/pranav.agarwal18/",
            linkedin: "https://www.linkedin.com/in/pranav-agarwal-535928227/",
          },
          {
            name: "Pushpak Jha",
            image: "./images/teams/pr_team/pushpak.jpg",
            designation: "Team Executive",
            phone: "+91 9654965888",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://instagram.com/pushpak.peace?igshid=Yzg5MTU1MDY=",
            linkedin: "https://www.linkedin.com/in/pushpak-kumar-jha-963192243",
          },
          {
            name: "Riddhi Mittal",
            image: "./images/teams/pr_team/riddhi.jpg",
            designation: "Team Executive",
            phone: "+91 8826219901",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://instagram.com/riddhi_mittal20?igshid=ZmZhODViOGI=",
            linkedin: "https://www.linkedin.com/in/riddhi-mittal-41858523b",
          },
          {
            name: "Manan Motiramani",
            image: "./images/teams/pr_team/manan.jpg",
            designation: "Team Executive",
            phone: "+91 7976810031",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "https://www.instagram.com/mananm_21/",
            linkedin: "https://www.linkedin.com/in/manan-motiramani-451699229/",
          },
        ],
      },
    ],
  },
  {
    team: "Event Management",
    leads: [
      {
        name: "Sahil Gupta",
        image: "./images/teams/events_team/sahil.jpg",
        designation: "Team Lead",
        phone: "+91 7015824452",
        mail: "20UCS166@LNMIIT.AC.IN",
        facebook: "/ourteam",
        instagram: "/ourteam",
        linkedin: "/ourteam",
      },
    ],
    members: [
      {
        subteam: "Group Leads & Members",
        members: [
          {
            name: "Mudit Choudhary",
            image: "./images/teams/events_team/mudit.jpg",
            designation: "Group Lead",
            phone: "+91 7840054325",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Saransh Jindal",
            image: "./images/teams/events_team/saransh.jpg",
            designation: "Group Lead",
            phone: "+91 8851625921",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Akash Mondal",
            image: "./images/teams/events_team/akash.jpg",
            designation: "Group Lead",
            phone: "+91 7498550574",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Ansh Pant",
            image: "./images/teams/events_team/ansh.jpg",
            designation: "Group Lead",
            phone: "+91 8595986243",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Siddharth Choudhary",
            image: "./images/teams/events_team/siddharth.jpg",
            designation: "Group Lead",
            phone: "+91 7052960505",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Chitransh Jaiswal",
            image: "./images/teams/events_team/chitransh.jpg",
            designation: "Group Lead",
            phone: "+91 7425920696",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Nanik Chaturvedi",
            image: "./images/teams/events_team/nanik.jpg",
            designation: "Team Executive",
            phone: "/ourteam",
            mail: "21ucc068@lnmiit.ac.in",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Maanas",
            image: "./images/teams/events_team/maanas.jpg",
            designation: "Team Executive",
            phone: "/ourteam",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Gautam Mittal",
            image: "./images/teams/events_team/gautam.jpg",
            designation: "Team Executive",
            phone: "/ourteam",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
          {
            name: "Chirag Mittal",
            image: "./images/teams/events_team/chirag.jpg",
            designation: "Team Executive",
            phone: "/ourteam",
            mail: "/ourteam",
            facebook: "/ourteam",
            instagram: "/ourteam",
            linkedin: "/ourteam",
          },
        ],
      },
    ],
  },
];